require_relative 'structure_standard'

module Mustafa
  module StructureLine
    module Structure
      module Standard
        module ConfinedMasonry
          module Catalog

            include Utils::Constants

            # Style number 1 is the basic red brick wall, RC column, and RC ring beam.
            CONFINED_MASONRY_STYLE_1 = {
              CONFINED_MASONRY_ELEMENT_NAME_COLUMN => COLUMN_STYLE_RC_COLUMN,
              CONFINED_MASONRY_ELEMENT_NAME_WALL => WALL_STYLE_BRICK_MASONRY,
              CONFINED_MASONRY_ELEMENT_NAME_RING_BEAM => RC_BEAM_STYLE_NORMAL,
            }

            CONFINED_MASONRY_STYLE_CATALOG = {
              STRUCTURE_STYLE_1 => CONFINED_MASONRY_STYLE_1
            }

            CONFINED_MASONRY_PRESENTATION_SIMPLE = {
              CONFINED_MASONRY_ELEMENT_NAME_COLUMN => ELEMENT_PRESENTATION_SIMPLE,
              CONFINED_MASONRY_ELEMENT_NAME_WALL => ELEMENT_PRESENTATION_SIMPLE,
              CONFINED_MASONRY_ELEMENT_NAME_RING_BEAM => ELEMENT_PRESENTATION_SIMPLE,
            }

            CONFINED_MASONRY_PRESENTATION_FULL = {
              CONFINED_MASONRY_ELEMENT_NAME_COLUMN => ELEMENT_PRESENTATION_FULL,
              CONFINED_MASONRY_ELEMENT_NAME_WALL => ELEMENT_PRESENTATION_FULL,
              CONFINED_MASONRY_ELEMENT_NAME_RING_BEAM => ELEMENT_PRESENTATION_FULL,
            }

            CONFINED_MASONRY_PRESENTATION_PARTIAL = {
              CONFINED_MASONRY_ELEMENT_NAME_COLUMN => COLUMN_PRESENTATION_PARTIAL_CONCRETE,
              CONFINED_MASONRY_ELEMENT_NAME_WALL => WALL_PRESENTATION_PARTIAL_PLASTER,
              CONFINED_MASONRY_ELEMENT_NAME_RING_BEAM => RC_BEAM_PRESENTATION_PARTIAL_CONCRETE,
            }

            CONFINED_MASONRY_PRESENTATION_SKELETON = {
              CONFINED_MASONRY_ELEMENT_NAME_COLUMN => COLUMN_PRESENTATION_NO_CONCRETE,
              CONFINED_MASONRY_ELEMENT_NAME_WALL => WALL_PRESENTATION_NO_PLASTER,
              CONFINED_MASONRY_ELEMENT_NAME_RING_BEAM => RC_BEAM_PRESENTATION_NO_CONCRETE,
            }

            CONFINED_MASONRY_PRESENTATION_CATALOG = {
              STRUCTURE_PRESENTATION_SIMPLE => CONFINED_MASONRY_PRESENTATION_SIMPLE,
              STRUCTURE_PRESENTATION_FULL => CONFINED_MASONRY_PRESENTATION_FULL,
              STRUCTURE_PRESENTATION_PARTIAL => CONFINED_MASONRY_PRESENTATION_PARTIAL,
              STRUCTURE_PRESENTATION_SKELETON => CONFINED_MASONRY_PRESENTATION_SKELETON
            }

          end
        end
      end
    end
  end
end